import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        {/*eslint-disable-next-line @next/next/no-sync-scripts*/}
        <script src="bower_components/firebaseui/dist/firebaseui.js"></script>
        {/*eslint-disable-next-line @next/next/no-css-tags*/}
        <link type="text/css" rel="stylesheet" href="bower_components/firebaseui/dist/firebaseui.css" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css' rel='stylesheet' />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
